### PR TITLE
Run docs doctests in travis

### PR DESCRIPTION
**Pull request by jimfulton**
Also added a travis egg cache t speed builds

### CODE REVIEW

**Comment by tseaver** [comment]
Wouldn't it be simpler just to run `tox` on Travis?

**Comment by jimfulton** [comment]
I have no idea. I don't use tox. This works. If you want to create a PR that uses tox, then go for it.

Whatever though, we need to start running the docs tests on travis (or stop running them elsewhere :)).

**Comment by jimfulton** [comment]
I see there's a tox.ini.  It only runs the docs tests for Python 2.7.

**Comment by jimfulton** [comment]
FWIW, I'm not a fan of sphinx doctest support nor of our doctests embedded in the docs. They mess up the docs.

If I were going to do this, I'd use manuel to make the docs testable, in which case they'd be run using the standard test runner.

**Pull request merged**
