### PR TITLE
Update changelog for #59

### PR DESCRIPTION
**Pull request by rouge8**
I'm not entirely sure what the release process is, but I was hoping this could get it started. :)

### CODE REVIEW

**Comment by jamadden** [comment]
The `zest.releaser` command 'fullrelease' should take care of everything. No need to manually make these sorts of changes (except if the change log hadn't been updated, then that does have to happen in a separate commit, although I think there is a zest.releaser helper command for that---ordinarily we update the changelog as part of the PR).

**Comment by rouge8** [comment]
Got it. Should I update this PR to do only the changelog updates and not the version bump?

**Comment by jamadden** [comment]
I would approve that 😄

**Comment by rouge8** [comment]
Done! I left the date as `2018-03-xx` in the changelog. Whoever uploads to PyPI should update that

**Comment by jamadden** [comment]
>  I left the date as 2018-03-xx in the changelog. Whoever uploads to PyPI should update that

zest.releaser handles that part too! (normally the date for the next release is "unreleased".)

**Comment by rouge8** [comment]
Fixed 😂

**Comment by rouge8** [comment]
@jamadden any chance you could do the release? :)

**Comment by jamadden** [comment]
I sure can! (I forgot I had PyPI rights to this project.)

**Pull request merged**
