### PR TITLE
Add changenote for #38 and bump version minor number.

### PR DESCRIPTION
**Pull request by jamadden**
Also whitespace cleanup in setup.py.

### CODE REVIEW

**Comment by jamadden** [comment]
Thanks! 

Could we get a PyPI release when convenient, please? I don't have permission to do so.

**Comment by icemac** [comment]
I neither do have the needed permissions. :-/

**Comment by mgedmin** [comment]
@jamadden: you now have the PyPI bit.

@icemac: I wasn't sure if your PyPI username matches your GitHub username or not.

**Comment by jamadden** [comment]
@mgedmin Thank you!

I've pushed 2.2.0 to PyPI.

**Comment by icemac** [comment]
@mgedmin Yes, my usernames on GitHub and PyPI are the same.

**Pull request merged**
